#!/usr/bin/env bash

. "$(dirname -- "$0")/pygmentize.env" 2>/dev/null || true
: "${PYGMENTIZE_HOST:=localhost}"
: "${PYGMENTIZE_PORT:=7879}"

# curl can’t mix query params with POST data,
# so we first encode the query and get the effective URL,
# then make the actual POST of stdin to that URL

args=()
files=()
for arg; do
    args+=(--data-urlencode "args=$arg")
    if [[ -f $arg ]]; then
        file=${arg//'\'/'\\'}
        file=${arg//'"'/'\"'}
        files+=(-F "file=@\"$file\";filename=\"$file\"")
    fi
done

# don’t actually connect, just write out the encoded URL
url=$(
    curl -s \
         --connect-to "$PYGMENTIZE_HOST:$PYGMENTIZE_PORT:localhost:0" \
         --write-out '%{url_effective}' \
         -G \
         "${args[@]}" \
         "http://$PYGMENTIZE_HOST:$PYGMENTIZE_PORT/"
   )

if [[ ! -v PYGMENTIZE_NO_STDIN ]]; then
    files+=(-F 'file=@/dev/stdin;filename=/dev/stdin')
fi

exec curl -f "${files[@]}" "$url"
